<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>se356_midterm</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MySql.Data" Version="9.7.0" />
    </ItemGroup>

</Project>
